/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyDocIdRouteImport } from './routes/verify.$docId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedOnboardingResultatRouteImport } from './routes/_authenticated/onboarding.resultat'
import { Route as AuthenticatedOnboardingProjetPretRouteImport } from './routes/_authenticated/onboarding.projet-pret'
import { Route as AuthenticatedOnboardingOrganisationRouteImport } from './routes/_authenticated/onboarding.organisation'
import { Route as AuthenticatedOnboardingEquipeRouteImport } from './routes/_authenticated/onboarding.equipe'
import { Route as AuthenticatedOnboardingContexteRouteImport } from './routes/_authenticated/onboarding.contexte'
import { Route as AuthenticatedAppReferentielRouteImport } from './routes/_authenticated/app.referentiel'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppCreditsRouteImport } from './routes/_authenticated/app.credits'
import { Route as AuthenticatedAppConsultantsRouteImport } from './routes/_authenticated/app.consultants'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicVerifyDocIdRouteImport } from './routes/api/public/verify.$docId'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/app.projects.new'
import { Route as AuthenticatedAppCreditsRetourRouteImport } from './routes/_authenticated/app.credits.retour'
import { Route as AuthenticatedAppComiteVersionsRouteImport } from './routes/_authenticated/app.comite.versions'
import { Route as AuthenticatedAppComitePublishRouteImport } from './routes/_authenticated/app.comite.publish'
import { Route as AuthenticatedAppComitePropositionsRouteImport } from './routes/_authenticated/app.comite.propositions'
import { Route as AuthenticatedAppComiteBeeOneRouteImport } from './routes/_authenticated/app.comite.bee-one'
import { Route as AuthenticatedAppBusinessPlansIdRouteImport } from './routes/_authenticated/app.business-plans.$id'
import { Route as AuthenticatedAppBudgetsIdRouteImport } from './routes/_authenticated/app.budgets.$id'
import { Route as AuthenticatedAppAdminUsersRouteImport } from './routes/_authenticated/app.admin.users'
import { Route as AuthenticatedAppAdminReferentielRouteImport } from './routes/_authenticated/app.admin.referentiel'
import { Route as AuthenticatedAppAdminPlansRouteImport } from './routes/_authenticated/app.admin.plans'
import { Route as AuthenticatedAppAdminOrganizationsRouteImport } from './routes/_authenticated/app.admin.organizations'
import { Route as AuthenticatedAppAdminCreditsRouteImport } from './routes/_authenticated/app.admin.credits'
import { Route as AuthenticatedAppAdminConsultantsRouteImport } from './routes/_authenticated/app.admin.consultants'
import { Route as AuthenticatedAppAdminAuditRouteImport } from './routes/_authenticated/app.admin.audit'
import { Route as AuthenticatedAppCreditsRequestsIdRouteImport } from './routes/_authenticated/app.credits.requests.$id'
import { Route as AuthenticatedAppAdminUsersIdRouteImport } from './routes/_authenticated/app.admin.users.$id'
import { Route as AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport } from './routes/_authenticated/app.projects.$id.prefaisabilite.$profilCode'

const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDocIdRoute = VerifyDocIdRouteImport.update({
  id: '/verify/$docId',
  path: '/verify/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOnboardingResultatRoute =
  AuthenticatedOnboardingResultatRouteImport.update({
    id: '/onboarding/resultat',
    path: '/onboarding/resultat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingProjetPretRoute =
  AuthenticatedOnboardingProjetPretRouteImport.update({
    id: '/onboarding/projet-pret',
    path: '/onboarding/projet-pret',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingOrganisationRoute =
  AuthenticatedOnboardingOrganisationRouteImport.update({
    id: '/onboarding/organisation',
    path: '/onboarding/organisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingEquipeRoute =
  AuthenticatedOnboardingEquipeRouteImport.update({
    id: '/onboarding/equipe',
    path: '/onboarding/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingContexteRoute =
  AuthenticatedOnboardingContexteRouteImport.update({
    id: '/onboarding/contexte',
    path: '/onboarding/contexte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReferentielRoute =
  AuthenticatedAppReferentielRouteImport.update({
    id: '/app/referentiel',
    path: '/app/referentiel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/app/inbox',
  path: '/app/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCreditsRoute = AuthenticatedAppCreditsRouteImport.update({
  id: '/app/credits',
  path: '/app/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppConsultantsRoute =
  AuthenticatedAppConsultantsRouteImport.update({
    id: '/app/consultants',
    path: '/app/consultants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyDocIdRoute = ApiPublicVerifyDocIdRouteImport.update({
  id: '/api/public/verify/$docId',
  path: '/api/public/verify/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/app/projects/new',
    path: '/app/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCreditsRetourRoute =
  AuthenticatedAppCreditsRetourRouteImport.update({
    id: '/retour',
    path: '/retour',
    getParentRoute: () => AuthenticatedAppCreditsRoute,
  } as any)
const AuthenticatedAppComiteVersionsRoute =
  AuthenticatedAppComiteVersionsRouteImport.update({
    id: '/app/comite/versions',
    path: '/app/comite/versions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppComitePublishRoute =
  AuthenticatedAppComitePublishRouteImport.update({
    id: '/app/comite/publish',
    path: '/app/comite/publish',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppComitePropositionsRoute =
  AuthenticatedAppComitePropositionsRouteImport.update({
    id: '/app/comite/propositions',
    path: '/app/comite/propositions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppComiteBeeOneRoute =
  AuthenticatedAppComiteBeeOneRouteImport.update({
    id: '/app/comite/bee-one',
    path: '/app/comite/bee-one',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBusinessPlansIdRoute =
  AuthenticatedAppBusinessPlansIdRouteImport.update({
    id: '/app/business-plans/$id',
    path: '/app/business-plans/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBudgetsIdRoute =
  AuthenticatedAppBudgetsIdRouteImport.update({
    id: '/app/budgets/$id',
    path: '/app/budgets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminUsersRoute =
  AuthenticatedAppAdminUsersRouteImport.update({
    id: '/app/admin/users',
    path: '/app/admin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminReferentielRoute =
  AuthenticatedAppAdminReferentielRouteImport.update({
    id: '/app/admin/referentiel',
    path: '/app/admin/referentiel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminPlansRoute =
  AuthenticatedAppAdminPlansRouteImport.update({
    id: '/app/admin/plans',
    path: '/app/admin/plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminOrganizationsRoute =
  AuthenticatedAppAdminOrganizationsRouteImport.update({
    id: '/app/admin/organizations',
    path: '/app/admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminCreditsRoute =
  AuthenticatedAppAdminCreditsRouteImport.update({
    id: '/app/admin/credits',
    path: '/app/admin/credits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminConsultantsRoute =
  AuthenticatedAppAdminConsultantsRouteImport.update({
    id: '/app/admin/consultants',
    path: '/app/admin/consultants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminAuditRoute =
  AuthenticatedAppAdminAuditRouteImport.update({
    id: '/app/admin/audit',
    path: '/app/admin/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCreditsRequestsIdRoute =
  AuthenticatedAppCreditsRequestsIdRouteImport.update({
    id: '/requests/$id',
    path: '/requests/$id',
    getParentRoute: () => AuthenticatedAppCreditsRoute,
  } as any)
const AuthenticatedAppAdminUsersIdRoute =
  AuthenticatedAppAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppAdminUsersRoute,
  } as any)
const AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute =
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport.update({
    id: '/app/projects/$id/prefaisabilite/$profilCode',
    path: '/app/projects/$id/prefaisabilite/$profilCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/verify/$docId': typeof VerifyDocIdRoute
  '/verify/': typeof VerifyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/consultants': typeof AuthenticatedAppConsultantsRoute
  '/app/credits': typeof AuthenticatedAppCreditsRouteWithChildren
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/onboarding/contexte': typeof AuthenticatedOnboardingContexteRoute
  '/onboarding/equipe': typeof AuthenticatedOnboardingEquipeRoute
  '/onboarding/organisation': typeof AuthenticatedOnboardingOrganisationRoute
  '/onboarding/projet-pret': typeof AuthenticatedOnboardingProjetPretRoute
  '/onboarding/resultat': typeof AuthenticatedOnboardingResultatRoute
  '/app/admin/audit': typeof AuthenticatedAppAdminAuditRoute
  '/app/admin/consultants': typeof AuthenticatedAppAdminConsultantsRoute
  '/app/admin/credits': typeof AuthenticatedAppAdminCreditsRoute
  '/app/admin/organizations': typeof AuthenticatedAppAdminOrganizationsRoute
  '/app/admin/plans': typeof AuthenticatedAppAdminPlansRoute
  '/app/admin/referentiel': typeof AuthenticatedAppAdminReferentielRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRouteWithChildren
  '/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/app/comite/bee-one': typeof AuthenticatedAppComiteBeeOneRoute
  '/app/comite/propositions': typeof AuthenticatedAppComitePropositionsRoute
  '/app/comite/publish': typeof AuthenticatedAppComitePublishRoute
  '/app/comite/versions': typeof AuthenticatedAppComiteVersionsRoute
  '/app/credits/retour': typeof AuthenticatedAppCreditsRetourRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/public/verify/$docId': typeof ApiPublicVerifyDocIdRoute
  '/app/admin/users/$id': typeof AuthenticatedAppAdminUsersIdRoute
  '/app/credits/requests/$id': typeof AuthenticatedAppCreditsRequestsIdRoute
  '/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/verify/$docId': typeof VerifyDocIdRoute
  '/verify': typeof VerifyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/consultants': typeof AuthenticatedAppConsultantsRoute
  '/app/credits': typeof AuthenticatedAppCreditsRouteWithChildren
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/onboarding/contexte': typeof AuthenticatedOnboardingContexteRoute
  '/onboarding/equipe': typeof AuthenticatedOnboardingEquipeRoute
  '/onboarding/organisation': typeof AuthenticatedOnboardingOrganisationRoute
  '/onboarding/projet-pret': typeof AuthenticatedOnboardingProjetPretRoute
  '/onboarding/resultat': typeof AuthenticatedOnboardingResultatRoute
  '/app/admin/audit': typeof AuthenticatedAppAdminAuditRoute
  '/app/admin/consultants': typeof AuthenticatedAppAdminConsultantsRoute
  '/app/admin/credits': typeof AuthenticatedAppAdminCreditsRoute
  '/app/admin/organizations': typeof AuthenticatedAppAdminOrganizationsRoute
  '/app/admin/plans': typeof AuthenticatedAppAdminPlansRoute
  '/app/admin/referentiel': typeof AuthenticatedAppAdminReferentielRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRouteWithChildren
  '/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/app/comite/bee-one': typeof AuthenticatedAppComiteBeeOneRoute
  '/app/comite/propositions': typeof AuthenticatedAppComitePropositionsRoute
  '/app/comite/publish': typeof AuthenticatedAppComitePublishRoute
  '/app/comite/versions': typeof AuthenticatedAppComiteVersionsRoute
  '/app/credits/retour': typeof AuthenticatedAppCreditsRetourRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/public/verify/$docId': typeof ApiPublicVerifyDocIdRoute
  '/app/admin/users/$id': typeof AuthenticatedAppAdminUsersIdRoute
  '/app/credits/requests/$id': typeof AuthenticatedAppCreditsRequestsIdRoute
  '/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/verify/$docId': typeof VerifyDocIdRoute
  '/verify/': typeof VerifyIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/consultants': typeof AuthenticatedAppConsultantsRoute
  '/_authenticated/app/credits': typeof AuthenticatedAppCreditsRouteWithChildren
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/_authenticated/onboarding/contexte': typeof AuthenticatedOnboardingContexteRoute
  '/_authenticated/onboarding/equipe': typeof AuthenticatedOnboardingEquipeRoute
  '/_authenticated/onboarding/organisation': typeof AuthenticatedOnboardingOrganisationRoute
  '/_authenticated/onboarding/projet-pret': typeof AuthenticatedOnboardingProjetPretRoute
  '/_authenticated/onboarding/resultat': typeof AuthenticatedOnboardingResultatRoute
  '/_authenticated/app/admin/audit': typeof AuthenticatedAppAdminAuditRoute
  '/_authenticated/app/admin/consultants': typeof AuthenticatedAppAdminConsultantsRoute
  '/_authenticated/app/admin/credits': typeof AuthenticatedAppAdminCreditsRoute
  '/_authenticated/app/admin/organizations': typeof AuthenticatedAppAdminOrganizationsRoute
  '/_authenticated/app/admin/plans': typeof AuthenticatedAppAdminPlansRoute
  '/_authenticated/app/admin/referentiel': typeof AuthenticatedAppAdminReferentielRoute
  '/_authenticated/app/admin/users': typeof AuthenticatedAppAdminUsersRouteWithChildren
  '/_authenticated/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/_authenticated/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/_authenticated/app/comite/bee-one': typeof AuthenticatedAppComiteBeeOneRoute
  '/_authenticated/app/comite/propositions': typeof AuthenticatedAppComitePropositionsRoute
  '/_authenticated/app/comite/publish': typeof AuthenticatedAppComitePublishRoute
  '/_authenticated/app/comite/versions': typeof AuthenticatedAppComiteVersionsRoute
  '/_authenticated/app/credits/retour': typeof AuthenticatedAppCreditsRetourRoute
  '/_authenticated/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/public/verify/$docId': typeof ApiPublicVerifyDocIdRoute
  '/_authenticated/app/admin/users/$id': typeof AuthenticatedAppAdminUsersIdRoute
  '/_authenticated/app/credits/requests/$id': typeof AuthenticatedAppCreditsRequestsIdRoute
  '/_authenticated/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/mentions-legales'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/settings'
    | '/invite/$token'
    | '/verify/$docId'
    | '/verify/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/consultants'
    | '/app/credits'
    | '/app/inbox'
    | '/app/referentiel'
    | '/onboarding/contexte'
    | '/onboarding/equipe'
    | '/onboarding/organisation'
    | '/onboarding/projet-pret'
    | '/onboarding/resultat'
    | '/app/admin/audit'
    | '/app/admin/consultants'
    | '/app/admin/credits'
    | '/app/admin/organizations'
    | '/app/admin/plans'
    | '/app/admin/referentiel'
    | '/app/admin/users'
    | '/app/budgets/$id'
    | '/app/business-plans/$id'
    | '/app/comite/bee-one'
    | '/app/comite/propositions'
    | '/app/comite/publish'
    | '/app/comite/versions'
    | '/app/credits/retour'
    | '/app/projects/new'
    | '/api/public/verify/$docId'
    | '/app/admin/users/$id'
    | '/app/credits/requests/$id'
    | '/app/projects/$id/prefaisabilite/$profilCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/mentions-legales'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/settings'
    | '/invite/$token'
    | '/verify/$docId'
    | '/verify'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/consultants'
    | '/app/credits'
    | '/app/inbox'
    | '/app/referentiel'
    | '/onboarding/contexte'
    | '/onboarding/equipe'
    | '/onboarding/organisation'
    | '/onboarding/projet-pret'
    | '/onboarding/resultat'
    | '/app/admin/audit'
    | '/app/admin/consultants'
    | '/app/admin/credits'
    | '/app/admin/organizations'
    | '/app/admin/plans'
    | '/app/admin/referentiel'
    | '/app/admin/users'
    | '/app/budgets/$id'
    | '/app/business-plans/$id'
    | '/app/comite/bee-one'
    | '/app/comite/propositions'
    | '/app/comite/publish'
    | '/app/comite/versions'
    | '/app/credits/retour'
    | '/app/projects/new'
    | '/api/public/verify/$docId'
    | '/app/admin/users/$id'
    | '/app/credits/requests/$id'
    | '/app/projects/$id/prefaisabilite/$profilCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/mentions-legales'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/verify/$docId'
    | '/verify/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/consultants'
    | '/_authenticated/app/credits'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/referentiel'
    | '/_authenticated/onboarding/contexte'
    | '/_authenticated/onboarding/equipe'
    | '/_authenticated/onboarding/organisation'
    | '/_authenticated/onboarding/projet-pret'
    | '/_authenticated/onboarding/resultat'
    | '/_authenticated/app/admin/audit'
    | '/_authenticated/app/admin/consultants'
    | '/_authenticated/app/admin/credits'
    | '/_authenticated/app/admin/organizations'
    | '/_authenticated/app/admin/plans'
    | '/_authenticated/app/admin/referentiel'
    | '/_authenticated/app/admin/users'
    | '/_authenticated/app/budgets/$id'
    | '/_authenticated/app/business-plans/$id'
    | '/_authenticated/app/comite/bee-one'
    | '/_authenticated/app/comite/propositions'
    | '/_authenticated/app/comite/publish'
    | '/_authenticated/app/comite/versions'
    | '/_authenticated/app/credits/retour'
    | '/_authenticated/app/projects/new'
    | '/api/public/verify/$docId'
    | '/_authenticated/app/admin/users/$id'
    | '/_authenticated/app/credits/requests/$id'
    | '/_authenticated/app/projects/$id/prefaisabilite/$profilCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  VerifyDocIdRoute: typeof VerifyDocIdRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicVerifyDocIdRoute: typeof ApiPublicVerifyDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$docId': {
      id: '/verify/$docId'
      path: '/verify/$docId'
      fullPath: '/verify/$docId'
      preLoaderRoute: typeof VerifyDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/resultat': {
      id: '/_authenticated/onboarding/resultat'
      path: '/onboarding/resultat'
      fullPath: '/onboarding/resultat'
      preLoaderRoute: typeof AuthenticatedOnboardingResultatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/projet-pret': {
      id: '/_authenticated/onboarding/projet-pret'
      path: '/onboarding/projet-pret'
      fullPath: '/onboarding/projet-pret'
      preLoaderRoute: typeof AuthenticatedOnboardingProjetPretRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/organisation': {
      id: '/_authenticated/onboarding/organisation'
      path: '/onboarding/organisation'
      fullPath: '/onboarding/organisation'
      preLoaderRoute: typeof AuthenticatedOnboardingOrganisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/equipe': {
      id: '/_authenticated/onboarding/equipe'
      path: '/onboarding/equipe'
      fullPath: '/onboarding/equipe'
      preLoaderRoute: typeof AuthenticatedOnboardingEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/contexte': {
      id: '/_authenticated/onboarding/contexte'
      path: '/onboarding/contexte'
      fullPath: '/onboarding/contexte'
      preLoaderRoute: typeof AuthenticatedOnboardingContexteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/referentiel': {
      id: '/_authenticated/app/referentiel'
      path: '/app/referentiel'
      fullPath: '/app/referentiel'
      preLoaderRoute: typeof AuthenticatedAppReferentielRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/app/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/credits': {
      id: '/_authenticated/app/credits'
      path: '/app/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof AuthenticatedAppCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/consultants': {
      id: '/_authenticated/app/consultants'
      path: '/app/consultants'
      fullPath: '/app/consultants'
      preLoaderRoute: typeof AuthenticatedAppConsultantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/$docId': {
      id: '/api/public/verify/$docId'
      path: '/api/public/verify/$docId'
      fullPath: '/api/public/verify/$docId'
      preLoaderRoute: typeof ApiPublicVerifyDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/projects/new': {
      id: '/_authenticated/app/projects/new'
      path: '/app/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/credits/retour': {
      id: '/_authenticated/app/credits/retour'
      path: '/retour'
      fullPath: '/app/credits/retour'
      preLoaderRoute: typeof AuthenticatedAppCreditsRetourRouteImport
      parentRoute: typeof AuthenticatedAppCreditsRoute
    }
    '/_authenticated/app/comite/versions': {
      id: '/_authenticated/app/comite/versions'
      path: '/app/comite/versions'
      fullPath: '/app/comite/versions'
      preLoaderRoute: typeof AuthenticatedAppComiteVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/comite/publish': {
      id: '/_authenticated/app/comite/publish'
      path: '/app/comite/publish'
      fullPath: '/app/comite/publish'
      preLoaderRoute: typeof AuthenticatedAppComitePublishRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/comite/propositions': {
      id: '/_authenticated/app/comite/propositions'
      path: '/app/comite/propositions'
      fullPath: '/app/comite/propositions'
      preLoaderRoute: typeof AuthenticatedAppComitePropositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/comite/bee-one': {
      id: '/_authenticated/app/comite/bee-one'
      path: '/app/comite/bee-one'
      fullPath: '/app/comite/bee-one'
      preLoaderRoute: typeof AuthenticatedAppComiteBeeOneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/business-plans/$id': {
      id: '/_authenticated/app/business-plans/$id'
      path: '/app/business-plans/$id'
      fullPath: '/app/business-plans/$id'
      preLoaderRoute: typeof AuthenticatedAppBusinessPlansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/budgets/$id': {
      id: '/_authenticated/app/budgets/$id'
      path: '/app/budgets/$id'
      fullPath: '/app/budgets/$id'
      preLoaderRoute: typeof AuthenticatedAppBudgetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/users': {
      id: '/_authenticated/app/admin/users'
      path: '/app/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AuthenticatedAppAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/referentiel': {
      id: '/_authenticated/app/admin/referentiel'
      path: '/app/admin/referentiel'
      fullPath: '/app/admin/referentiel'
      preLoaderRoute: typeof AuthenticatedAppAdminReferentielRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/plans': {
      id: '/_authenticated/app/admin/plans'
      path: '/app/admin/plans'
      fullPath: '/app/admin/plans'
      preLoaderRoute: typeof AuthenticatedAppAdminPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/organizations': {
      id: '/_authenticated/app/admin/organizations'
      path: '/app/admin/organizations'
      fullPath: '/app/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAppAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/credits': {
      id: '/_authenticated/app/admin/credits'
      path: '/app/admin/credits'
      fullPath: '/app/admin/credits'
      preLoaderRoute: typeof AuthenticatedAppAdminCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/consultants': {
      id: '/_authenticated/app/admin/consultants'
      path: '/app/admin/consultants'
      fullPath: '/app/admin/consultants'
      preLoaderRoute: typeof AuthenticatedAppAdminConsultantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/audit': {
      id: '/_authenticated/app/admin/audit'
      path: '/app/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/credits/requests/$id': {
      id: '/_authenticated/app/credits/requests/$id'
      path: '/requests/$id'
      fullPath: '/app/credits/requests/$id'
      preLoaderRoute: typeof AuthenticatedAppCreditsRequestsIdRouteImport
      parentRoute: typeof AuthenticatedAppCreditsRoute
    }
    '/_authenticated/app/admin/users/$id': {
      id: '/_authenticated/app/admin/users/$id'
      path: '/$id'
      fullPath: '/app/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminUsersRoute
    }
    '/_authenticated/app/projects/$id/prefaisabilite/$profilCode': {
      id: '/_authenticated/app/projects/$id/prefaisabilite/$profilCode'
      path: '/app/projects/$id/prefaisabilite/$profilCode'
      fullPath: '/app/projects/$id/prefaisabilite/$profilCode'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAppCreditsRouteChildren {
  AuthenticatedAppCreditsRetourRoute: typeof AuthenticatedAppCreditsRetourRoute
  AuthenticatedAppCreditsRequestsIdRoute: typeof AuthenticatedAppCreditsRequestsIdRoute
}

const AuthenticatedAppCreditsRouteChildren: AuthenticatedAppCreditsRouteChildren =
  {
    AuthenticatedAppCreditsRetourRoute: AuthenticatedAppCreditsRetourRoute,
    AuthenticatedAppCreditsRequestsIdRoute:
      AuthenticatedAppCreditsRequestsIdRoute,
  }

const AuthenticatedAppCreditsRouteWithChildren =
  AuthenticatedAppCreditsRoute._addFileChildren(
    AuthenticatedAppCreditsRouteChildren,
  )

interface AuthenticatedAppAdminUsersRouteChildren {
  AuthenticatedAppAdminUsersIdRoute: typeof AuthenticatedAppAdminUsersIdRoute
}

const AuthenticatedAppAdminUsersRouteChildren: AuthenticatedAppAdminUsersRouteChildren =
  {
    AuthenticatedAppAdminUsersIdRoute: AuthenticatedAppAdminUsersIdRoute,
  }

const AuthenticatedAppAdminUsersRouteWithChildren =
  AuthenticatedAppAdminUsersRoute._addFileChildren(
    AuthenticatedAppAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAppConsultantsRoute: typeof AuthenticatedAppConsultantsRoute
  AuthenticatedAppCreditsRoute: typeof AuthenticatedAppCreditsRouteWithChildren
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppReferentielRoute: typeof AuthenticatedAppReferentielRoute
  AuthenticatedOnboardingContexteRoute: typeof AuthenticatedOnboardingContexteRoute
  AuthenticatedOnboardingEquipeRoute: typeof AuthenticatedOnboardingEquipeRoute
  AuthenticatedOnboardingOrganisationRoute: typeof AuthenticatedOnboardingOrganisationRoute
  AuthenticatedOnboardingProjetPretRoute: typeof AuthenticatedOnboardingProjetPretRoute
  AuthenticatedOnboardingResultatRoute: typeof AuthenticatedOnboardingResultatRoute
  AuthenticatedAppAdminAuditRoute: typeof AuthenticatedAppAdminAuditRoute
  AuthenticatedAppAdminConsultantsRoute: typeof AuthenticatedAppAdminConsultantsRoute
  AuthenticatedAppAdminCreditsRoute: typeof AuthenticatedAppAdminCreditsRoute
  AuthenticatedAppAdminOrganizationsRoute: typeof AuthenticatedAppAdminOrganizationsRoute
  AuthenticatedAppAdminPlansRoute: typeof AuthenticatedAppAdminPlansRoute
  AuthenticatedAppAdminReferentielRoute: typeof AuthenticatedAppAdminReferentielRoute
  AuthenticatedAppAdminUsersRoute: typeof AuthenticatedAppAdminUsersRouteWithChildren
  AuthenticatedAppBudgetsIdRoute: typeof AuthenticatedAppBudgetsIdRoute
  AuthenticatedAppBusinessPlansIdRoute: typeof AuthenticatedAppBusinessPlansIdRoute
  AuthenticatedAppComiteBeeOneRoute: typeof AuthenticatedAppComiteBeeOneRoute
  AuthenticatedAppComitePropositionsRoute: typeof AuthenticatedAppComitePropositionsRoute
  AuthenticatedAppComitePublishRoute: typeof AuthenticatedAppComitePublishRoute
  AuthenticatedAppComiteVersionsRoute: typeof AuthenticatedAppComiteVersionsRoute
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute: typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAppConsultantsRoute: AuthenticatedAppConsultantsRoute,
  AuthenticatedAppCreditsRoute: AuthenticatedAppCreditsRouteWithChildren,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppReferentielRoute: AuthenticatedAppReferentielRoute,
  AuthenticatedOnboardingContexteRoute: AuthenticatedOnboardingContexteRoute,
  AuthenticatedOnboardingEquipeRoute: AuthenticatedOnboardingEquipeRoute,
  AuthenticatedOnboardingOrganisationRoute:
    AuthenticatedOnboardingOrganisationRoute,
  AuthenticatedOnboardingProjetPretRoute:
    AuthenticatedOnboardingProjetPretRoute,
  AuthenticatedOnboardingResultatRoute: AuthenticatedOnboardingResultatRoute,
  AuthenticatedAppAdminAuditRoute: AuthenticatedAppAdminAuditRoute,
  AuthenticatedAppAdminConsultantsRoute: AuthenticatedAppAdminConsultantsRoute,
  AuthenticatedAppAdminCreditsRoute: AuthenticatedAppAdminCreditsRoute,
  AuthenticatedAppAdminOrganizationsRoute:
    AuthenticatedAppAdminOrganizationsRoute,
  AuthenticatedAppAdminPlansRoute: AuthenticatedAppAdminPlansRoute,
  AuthenticatedAppAdminReferentielRoute: AuthenticatedAppAdminReferentielRoute,
  AuthenticatedAppAdminUsersRoute: AuthenticatedAppAdminUsersRouteWithChildren,
  AuthenticatedAppBudgetsIdRoute: AuthenticatedAppBudgetsIdRoute,
  AuthenticatedAppBusinessPlansIdRoute: AuthenticatedAppBusinessPlansIdRoute,
  AuthenticatedAppComiteBeeOneRoute: AuthenticatedAppComiteBeeOneRoute,
  AuthenticatedAppComitePropositionsRoute:
    AuthenticatedAppComitePropositionsRoute,
  AuthenticatedAppComitePublishRoute: AuthenticatedAppComitePublishRoute,
  AuthenticatedAppComiteVersionsRoute: AuthenticatedAppComiteVersionsRoute,
  AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute:
    AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InviteTokenRoute: InviteTokenRoute,
  VerifyDocIdRoute: VerifyDocIdRoute,
  VerifyIndexRoute: VerifyIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicVerifyDocIdRoute: ApiPublicVerifyDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
