/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyDocIdRouteImport } from './routes/verify.$docId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAppReferentielRouteImport } from './routes/_authenticated/app.referentiel'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicVerifyDocIdRouteImport } from './routes/api/public/verify.$docId'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/app.projects.new'
import { Route as AuthenticatedAppBusinessPlansIdRouteImport } from './routes/_authenticated/app.business-plans.$id'
import { Route as AuthenticatedAppBudgetsIdRouteImport } from './routes/_authenticated/app.budgets.$id'
import { Route as AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport } from './routes/_authenticated/app.projects.$id.prefaisabilite.$profilCode'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyDocIdRoute = VerifyDocIdRouteImport.update({
  id: '/verify/$docId',
  path: '/verify/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppReferentielRoute =
  AuthenticatedAppReferentielRouteImport.update({
    id: '/app/referentiel',
    path: '/app/referentiel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyDocIdRoute = ApiPublicVerifyDocIdRouteImport.update({
  id: '/api/public/verify/$docId',
  path: '/api/public/verify/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/app/projects/new',
    path: '/app/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBusinessPlansIdRoute =
  AuthenticatedAppBusinessPlansIdRouteImport.update({
    id: '/app/business-plans/$id',
    path: '/app/business-plans/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBudgetsIdRoute =
  AuthenticatedAppBudgetsIdRouteImport.update({
    id: '/app/budgets/$id',
    path: '/app/budgets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute =
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport.update({
    id: '/app/projects/$id/prefaisabilite/$profilCode',
    path: '/app/projects/$id/prefaisabilite/$profilCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/verify/$docId': typeof VerifyDocIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/public/verify/$docId': typeof ApiPublicVerifyDocIdRoute
  '/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/verify/$docId': typeof VerifyDocIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/public/verify/$docId': typeof ApiPublicVerifyDocIdRoute
  '/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/verify/$docId': typeof VerifyDocIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/_authenticated/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/_authenticated/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/_authenticated/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/api/public/verify/$docId': typeof ApiPublicVerifyDocIdRoute
  '/_authenticated/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/settings'
    | '/invite/$token'
    | '/verify/$docId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/referentiel'
    | '/app/budgets/$id'
    | '/app/business-plans/$id'
    | '/app/projects/new'
    | '/api/public/verify/$docId'
    | '/app/projects/$id/prefaisabilite/$profilCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard'
    | '/settings'
    | '/invite/$token'
    | '/verify/$docId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/referentiel'
    | '/app/budgets/$id'
    | '/app/business-plans/$id'
    | '/app/projects/new'
    | '/api/public/verify/$docId'
    | '/app/projects/$id/prefaisabilite/$profilCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/verify/$docId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/referentiel'
    | '/_authenticated/app/budgets/$id'
    | '/_authenticated/app/business-plans/$id'
    | '/_authenticated/app/projects/new'
    | '/api/public/verify/$docId'
    | '/_authenticated/app/projects/$id/prefaisabilite/$profilCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  InviteTokenRoute: typeof InviteTokenRoute
  VerifyDocIdRoute: typeof VerifyDocIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicVerifyDocIdRoute: typeof ApiPublicVerifyDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$docId': {
      id: '/verify/$docId'
      path: '/verify/$docId'
      fullPath: '/verify/$docId'
      preLoaderRoute: typeof VerifyDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/referentiel': {
      id: '/_authenticated/app/referentiel'
      path: '/app/referentiel'
      fullPath: '/app/referentiel'
      preLoaderRoute: typeof AuthenticatedAppReferentielRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/$docId': {
      id: '/api/public/verify/$docId'
      path: '/api/public/verify/$docId'
      fullPath: '/api/public/verify/$docId'
      preLoaderRoute: typeof ApiPublicVerifyDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/projects/new': {
      id: '/_authenticated/app/projects/new'
      path: '/app/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/business-plans/$id': {
      id: '/_authenticated/app/business-plans/$id'
      path: '/app/business-plans/$id'
      fullPath: '/app/business-plans/$id'
      preLoaderRoute: typeof AuthenticatedAppBusinessPlansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/budgets/$id': {
      id: '/_authenticated/app/budgets/$id'
      path: '/app/budgets/$id'
      fullPath: '/app/budgets/$id'
      preLoaderRoute: typeof AuthenticatedAppBudgetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$id/prefaisabilite/$profilCode': {
      id: '/_authenticated/app/projects/$id/prefaisabilite/$profilCode'
      path: '/app/projects/$id/prefaisabilite/$profilCode'
      fullPath: '/app/projects/$id/prefaisabilite/$profilCode'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAppReferentielRoute: typeof AuthenticatedAppReferentielRoute
  AuthenticatedAppBudgetsIdRoute: typeof AuthenticatedAppBudgetsIdRoute
  AuthenticatedAppBusinessPlansIdRoute: typeof AuthenticatedAppBusinessPlansIdRoute
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute: typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAppReferentielRoute: AuthenticatedAppReferentielRoute,
  AuthenticatedAppBudgetsIdRoute: AuthenticatedAppBudgetsIdRoute,
  AuthenticatedAppBusinessPlansIdRoute: AuthenticatedAppBusinessPlansIdRoute,
  AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute:
    AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  InviteTokenRoute: InviteTokenRoute,
  VerifyDocIdRoute: VerifyDocIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicVerifyDocIdRoute: ApiPublicVerifyDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
