/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppReferentielRouteImport } from './routes/_authenticated/app.referentiel'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated/app.projects.new'
import { Route as AuthenticatedAppBusinessPlansIdRouteImport } from './routes/_authenticated/app.business-plans.$id'
import { Route as AuthenticatedAppBudgetsIdRouteImport } from './routes/_authenticated/app.budgets.$id'
import { Route as AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport } from './routes/_authenticated/app.projects.$id.prefaisabilite.$profilCode'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReferentielRoute =
  AuthenticatedAppReferentielRouteImport.update({
    id: '/app/referentiel',
    path: '/app/referentiel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/app/projects/new',
    path: '/app/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBusinessPlansIdRoute =
  AuthenticatedAppBusinessPlansIdRouteImport.update({
    id: '/app/business-plans/$id',
    path: '/app/business-plans/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBudgetsIdRoute =
  AuthenticatedAppBudgetsIdRouteImport.update({
    id: '/app/budgets/$id',
    path: '/app/budgets/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute =
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport.update({
    id: '/app/projects/$id/prefaisabilite/$profilCode',
    path: '/app/projects/$id/prefaisabilite/$profilCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/app/referentiel': typeof AuthenticatedAppReferentielRoute
  '/_authenticated/app/budgets/$id': typeof AuthenticatedAppBudgetsIdRoute
  '/_authenticated/app/business-plans/$id': typeof AuthenticatedAppBusinessPlansIdRoute
  '/_authenticated/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/_authenticated/app/projects/$id/prefaisabilite/$profilCode': typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/invite/$token'
    | '/app/referentiel'
    | '/app/budgets/$id'
    | '/app/business-plans/$id'
    | '/app/projects/new'
    | '/app/projects/$id/prefaisabilite/$profilCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/invite/$token'
    | '/app/referentiel'
    | '/app/budgets/$id'
    | '/app/business-plans/$id'
    | '/app/projects/new'
    | '/app/projects/$id/prefaisabilite/$profilCode'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/_authenticated/app/referentiel'
    | '/_authenticated/app/budgets/$id'
    | '/_authenticated/app/business-plans/$id'
    | '/_authenticated/app/projects/new'
    | '/_authenticated/app/projects/$id/prefaisabilite/$profilCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/referentiel': {
      id: '/_authenticated/app/referentiel'
      path: '/app/referentiel'
      fullPath: '/app/referentiel'
      preLoaderRoute: typeof AuthenticatedAppReferentielRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/new': {
      id: '/_authenticated/app/projects/new'
      path: '/app/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/business-plans/$id': {
      id: '/_authenticated/app/business-plans/$id'
      path: '/app/business-plans/$id'
      fullPath: '/app/business-plans/$id'
      preLoaderRoute: typeof AuthenticatedAppBusinessPlansIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/budgets/$id': {
      id: '/_authenticated/app/budgets/$id'
      path: '/app/budgets/$id'
      fullPath: '/app/budgets/$id'
      preLoaderRoute: typeof AuthenticatedAppBudgetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$id/prefaisabilite/$profilCode': {
      id: '/_authenticated/app/projects/$id/prefaisabilite/$profilCode'
      path: '/app/projects/$id/prefaisabilite/$profilCode'
      fullPath: '/app/projects/$id/prefaisabilite/$profilCode'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAppReferentielRoute: typeof AuthenticatedAppReferentielRoute
  AuthenticatedAppBudgetsIdRoute: typeof AuthenticatedAppBudgetsIdRoute
  AuthenticatedAppBusinessPlansIdRoute: typeof AuthenticatedAppBusinessPlansIdRoute
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute: typeof AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAppReferentielRoute: AuthenticatedAppReferentielRoute,
  AuthenticatedAppBudgetsIdRoute: AuthenticatedAppBudgetsIdRoute,
  AuthenticatedAppBusinessPlansIdRoute: AuthenticatedAppBusinessPlansIdRoute,
  AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute:
    AuthenticatedAppProjectsIdPrefaisabiliteProfilCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
